"""End-to-end pipeline: diagnose -> patch -> verify -> PR (or diagnosis-only)."""

from __future__ import annotations

import logging

from app.config import Settings
from app.db import RunStore
from app.github_client import GithubClient
from app.llm import LLMClient
from app.models import (
    Attempt,
    Diagnosis,
    FailureContext,
    FailureType,
    RunRecord,
    RunStatus,
    VerificationResult,
    WorkflowRunRef,
)
from app.patcher import PatchValidationError, validate_patch
from app.sandbox import Sandbox

logger = logging.getLogger(__name__)

FIXCI_BRANCH_PREFIX = "fixci/"


def build_pr_title(diagnosis: Diagnosis) -> str:
    """Short, human-readable PR title derived from the root cause."""
    cause = diagnosis.root_cause.strip().splitlines()[0] if diagnosis.root_cause.strip() else "CI failure"
    if len(cause) > 60:
        cause = cause[:57].rstrip() + "..."
    return f"FixCI: {cause}"


def build_pr_body(
    context: FailureContext,
    diagnosis: Diagnosis,
    verification: VerificationResult,
    attempts: int,
) -> str:
    """Compose the fix-PR description including verification evidence."""
    files = "\n".join(f"- `{path}`" for path in sorted(verification.patched_files)) or "- (none)"
    evidence = verification.output_tail.strip() or "(no output captured)"
    return f"""## FixCI automated fix

**Root cause:** {diagnosis.root_cause}

**What changed:** {len(verification.patched_files)} file(s)
{files}

**Confidence:** {diagnosis.confidence.value}

**Verification evidence** (re-ran the failing command in an isolated Docker sandbox):
```
$ {verification.command}
{evidence}
```

**Attempts used:** {attempts}

---
> ⚠️ **This change was generated by FixCI and verified automatically, but a human
> should review it before merging.** FixCI never auto-merges and never pushes to
> the original branch. The patch changes {len(verification.patched_files)} file(s).
"""


def build_diagnosis_comment(
    context: FailureContext,
    diagnosis: Diagnosis | None,
    attempts: int,
    note: str = "",
) -> str:
    """Compose the diagnosis-only comment (no patch pushed)."""
    if diagnosis is not None:
        body = (
            f"**Root cause:** {diagnosis.root_cause}\n\n"
            f"**Suggested fix:** {diagnosis.explanation}\n\n"
            f"**Confidence:** {diagnosis.confidence.value}"
        )
    else:
        body = "FixCI could not produce a reliable diagnosis for this failure."
    if note:
        body += f"\n\n**Why no patch:** {note}"
    return (
        "## FixCI diagnosis (unverified — no patch pushed)\n\n"
        f"{body}\n\n"
        f"**Classification:** `{context.failure_type.value}`\n"
        f"**Attempts used:** {attempts}\n\n"
        "> This is a diagnosis only. FixCI did not verify a patch, so it pushed "
        "nothing. A human should make the change manually."
    )


class Orchestrator:
    """Runs the FixCI pipeline for one failed workflow run."""

    def __init__(
        self,
        settings: Settings,
        store: RunStore,
        client: GithubClient,
        llm: LLMClient,
        sandbox: Sandbox,
    ) -> None:
        self.settings = settings
        self.store = store
        self.client = client
        self.llm = llm
        self.sandbox = sandbox

    # -- public -------------------------------------------------------------

    def process(self, run: WorkflowRunRef, workflow_path: str | None = None) -> RunRecord:
        """Execute the pipeline and return the terminal run record."""
        if self.store.is_terminal(run.run_id):
            logger.info("Run %s already reached a terminal state; skipping", run.run_id)
            return RunRecord(
                run_id=run.run_id, repo_full_name=run.repo_full_name, status=RunStatus.skipped
            )

        record = RunRecord(
            run_id=run.run_id, repo_full_name=run.repo_full_name, status=RunStatus.received
        )
        self.store.upsert(record)

        try:
            context = self.client.build_failure_context(run, workflow_path)
        except Exception as exc:  # noqa: BLE001 - surface any collection failure
            logger.exception("Failed to collect context for run %s", run.run_id)
            return self._finish(record, RunStatus.failed, detail=f"context collection failed: {exc}")

        record.failure_type = context.failure_type
        record.status = RunStatus.diagnosing
        self.store.upsert(record)

        if context.failure_type == FailureType.unsupported:
            return self._diagnosis_only(
                record, context, note="failure type is outside FixCI's supported scope"
            )

        return self._fix_loop(record, context)

    # -- internals ----------------------------------------------------------

    def _fix_loop(self, record: RunRecord, context: FailureContext) -> RunRecord:
        previous: Attempt | None = None
        last_diagnosis: Diagnosis | None = None

        for index in range(1, self.settings.max_attempts + 1):
            record.attempts = index
            record.status = RunStatus.fixing
            self.store.upsert(record)

            try:
                diagnosis = self.llm.diagnose(context, previous)
            except Exception as exc:  # noqa: BLE001
                logger.warning("LLM diagnosis failed on attempt %s: %s", index, exc)
                previous = Attempt(index=index, error=f"LLM error: {exc}")
                continue
            last_diagnosis = diagnosis
            record.root_cause = diagnosis.root_cause

            if diagnosis.is_patch_free():
                return self._diagnosis_only(
                    record, context, note="the model judged no safe automated fix exists",
                    diagnosis=diagnosis,
                )

            try:
                validate_patch(diagnosis.patch)
            except PatchValidationError as exc:
                logger.info("Rejected patch on attempt %s: %s", index, exc)
                previous = Attempt(index=index, diagnosis=diagnosis, error=f"patch rejected: {exc}")
                continue

            verification = self.sandbox.run(
                context, diagnosis, installation_token=self.client.installation_token()
            )
            logger.info(
                "Attempt %s verification passed=%s (%s)", index, verification.passed, verification.error
            )

            if verification.passed and verification.patched_files:
                return self._open_pr(record, context, diagnosis, verification, attempts=index)

            previous = Attempt(index=index, diagnosis=diagnosis, verification=verification)

        # All attempts exhausted: never push an unverified patch.
        return self._diagnosis_only(
            record,
            context,
            note="the patch could not be verified in the sandbox within the retry budget",
            diagnosis=last_diagnosis,
        )

    def _open_pr(
        self,
        record: RunRecord,
        context: FailureContext,
        diagnosis: Diagnosis,
        verification: VerificationResult,
        attempts: int,
    ) -> RunRecord:
        branch = f"{FIXCI_BRANCH_PREFIX}fix-{context.run.run_id}"
        title = build_pr_title(diagnosis)
        body = build_pr_body(context, diagnosis, verification, attempts)
        try:
            pr_url = self.client.create_fix_pr(
                branch=branch,
                base_branch=context.run.head_branch,
                base_sha=context.run.head_sha,
                title=title,
                body=body,
                patched_files=verification.patched_files,
                commit_message=f"{title}\n\nVerified in an isolated Docker sandbox.",
            )
        except Exception as exc:  # noqa: BLE001
            logger.exception("Failed to open fix PR for run %s", context.run.run_id)
            return self._finish(record, RunStatus.failed, attempts=attempts, detail=f"PR creation failed: {exc}")

        record.pr_url = pr_url
        self._comment(
            context,
            f"FixCI opened a verified fix PR: {pr_url}\n\n"
            f"Root cause: {diagnosis.root_cause}\n\n"
            f"Verification: `{verification.command}` now passes (attempt {attempts}).",
        )
        return self._finish(record, RunStatus.pr_opened, attempts=attempts, pr_url=pr_url)

    def _diagnosis_only(
        self,
        record: RunRecord,
        context: FailureContext,
        note: str,
        diagnosis: Diagnosis | None = None,
    ) -> RunRecord:
        if diagnosis is None:
            try:
                diagnosis = self.llm.diagnose(context)
                record.root_cause = diagnosis.root_cause
            except Exception as exc:  # noqa: BLE001
                logger.warning("Diagnosis-only LLM call failed: %s", exc)

        body = build_diagnosis_comment(context, diagnosis, record.attempts, note)
        self._comment(context, body)
        return self._finish(record, RunStatus.diagnosis_only, detail=note)

    def _comment(self, context: FailureContext, body: str) -> None:
        target = context.run.pr_number
        if target is None:
            target = self.client.find_pr_for_branch(context.run.head_branch)
        if target is None:
            logger.info("No PR to comment on for run %s", context.run.run_id)
            return
        try:
            self.client.post_comment(target, body)
        except Exception:  # noqa: BLE001 - commenting is best-effort
            logger.exception("Failed to post comment on #%s", target)

    def _finish(
        self,
        record: RunRecord,
        status: RunStatus,
        attempts: int | None = None,
        detail: str | None = None,
        pr_url: str | None = None,
    ) -> RunRecord:
        record.status = status
        if attempts is not None:
            record.attempts = attempts
        if detail is not None:
            record.detail = detail
        if pr_url is not None:
            record.pr_url = pr_url
        self.store.upsert(record)
        return record
